packageDescription: "model package for generated code"
packageHomepage: "https://github.com/appox/mars-flutter"   
packageVersion: "{{ ~.project.builder.version }}+{{ ~.builder.buildNumber }}"

# fuer die ref. auf config. (test-dep - fuer Reihenfolge.)
layout.config.packageName: mars_layout_base_published_projects_config