# base properties fuer layouts

layout.packageName: "de.appcosmos.base.app_start"
layout.instanceGroup: "baseAppStart"

layout.config.packageName: mars_layout_base_app_start_config
layout.config.classPrefix: Ybac

layout.model.packageName: mars_layout_base_app_start_model
layout.model.classPrefix: Ybam

layout.tag.packageName: mars_layout_base_app_start_tags
layout.tag.classPrefix: Ybat