# package  default fuer _build_ 
# 
packageDescription: "TBD"
packageHomepage: "https://github.com/appox/mars-flutter"   
packageVersion: "{{ ~.project.builder.version }}+{{ ~.builder.buildNumber }}"
