# package  default fuer _mars_ 
# 
packageDescription: "TBD"
packageHomepage: "https://github.com/appox/mars-flutter"   
packageVersion: "{{ ~.project.mars-flutter.version }}+{{ ~.mars-flutter.buildNumber }}"
