# base properties fuer layouts

# fuer die ref. auf config. (test-dep - fuer Reihenfolge.)
layout.config.packageName: mars_layout_base_published_projects_config
layout.model.packageName: mars_layout_base_published_projects_model