# base properties fuer layouts

# fuer die ref. auf config. (test-dep - fuer Reihenfolge.)
layout.config.packageName: mars_layout_base_published_projects_config
layout.config.classPrefix: Ybpp

layout.model.packageName: mars_layout_base_published_projects_model
layout.model.classPrefix: Ybpm

layout.tag.packageName: mars_msc_markup_tags_base_published_projects
layout.tag.classPrefix: Ybpt