# base properties fuer layouts

layout.packageName: "de.appcosmos.base.kee_pass"
layout.instanceGroup: "baseKeePass"

layout.config.packageName: mars_layout_base_kee_pass_config
layout.config.classPrefix: Ybkc

layout.model.packageName: mars_layout_base_kee_pass_model
layout.model.classPrefix: Ybkm

layout.tag.packageName: mars_layout_base_kee_pass_tags
layout.tag.classPrefix: Ybkt